name: .NET

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Clean
      run: dotnet clean
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: publish OpenAI.GPT3 
      id: publish_nuget_OpenAI_GPT3
      uses: alirezanet/publish-nuget@v3.0.3
      with:
          PROJECT_FILE_PATH: OpenAI.SDK\OpenAI.GPT3.csproj
          NUGET_KEY: ${{secrets.NUGET_KEY}}
